from __future__ import annotations

from typing import List, Dict, Any

from utils.logging_config import get_logger

logger = get_logger(__name__)


class OrderExecutor:
    """Executes market orders generated by the TradeGenerator."""

    def __init__(self, binance_client) -> None:
        self.binance_client = binance_client

    async def execute_orders(self, orders) -> List[Dict[str, Any]]:
        results: List[Dict[str, Any]] = []
        for instruction in orders:
            if instruction.quantity <= 0:
                logger.warning(
                    "Skipping zero-quantity order | symbol=%s", instruction.symbol
                )
                continue
            try:
                response = await self.binance_client.create_order(
                    symbol=instruction.symbol,
                    order_type="market",
                    side=instruction.side,
                    amount=instruction.quantity,
                )
                results.append(
                    {
                        "status": "success",
                        "symbol": instruction.symbol,
                        "side": instruction.side,
                        "quantity": instruction.quantity,
                        "target_weight": instruction.target_weight,
                        "response": response,
                    }
                )
            except Exception as exc:
                logger.error("Order execution failed for %s: %s", instruction.symbol, exc)
                results.append(
                    {
                        "status": "error",
                        "symbol": instruction.symbol,
                        "side": instruction.side,
                        "quantity": instruction.quantity,
                        "reason": str(exc),
                    }
                )
        return results
