from dataclasses import dataclass
from typing import Dict, Any, Optional

@dataclass
class TradeSignal:
    """
    A class representing a trading signal generated by a strategy.
    Contains only the essential information needed for a trading signal.
    """
    action: str  # "open" or "close"
    side: str  # "buy" or "sell"
    symbol: str  # Trading pair symbol (e.g., "BTCUSDT")
    strategy_id: str  # ID of the strategy that generated the signal
    metadata: Dict[str, Any]  # Additional information about the signal
    
    def __post_init__(self):
        """
        Validate the signal parameters.
        """
        if self.action not in ["open", "close"]:
            raise ValueError("Action must be either 'open' or 'close'")
            
        if self.side not in ["buy", "sell"]:
            raise ValueError("Side must be either 'buy' or 'sell'")
            
        if not self.symbol:
            raise ValueError("Symbol must be specified")
            
        if not self.strategy_id:
            raise ValueError("Strategy ID must be specified")
    
    # Strategy information
    signal_confidence: float  # Confidence level of the signal (0.0 to 1.0)
    
    # Additional information
    timestamp: int = 0  # Unix timestamp in milliseconds
    
    
   