from dataclasses import dataclass
from typing import Dict, Any, Optional

@dataclass
class TradeSignal:
    """A class representing a trading signal generated by a strategy.
    
    This class encapsulates all required information for futures trading signals,
    including action type, direction, and metadata.
    
    Attributes:
        action (str): Trading action to take - "open", "exit", or "hold".
        side (str): Direction of the trade - "buy", "sell", or "none" (for hold).
        symbol (str): Trading pair symbol (e.g., "BTCUSDT").
        strategy_id (str): ID of the strategy that generated the signal.
        metadata (Dict[str, Any]): Additional information about the signal.
        signal_confidence (float): Confidence level of the signal (0.0 to 1.0).
        timestamp (int, optional): Unix timestamp in milliseconds. Defaults to 0.
        
    Valid signal combinations for futures trading:
        - open/buy: Enter long position
        - open/sell: Enter short position
        - exit/sell: Exit long position
        - exit/buy: Exit short position
        - hold/none: No action needed (market conditions stable)
    """
    action: str  # "open", "exit", or "hold"
    side: str  # "buy", "sell", or "none" (for hold)
    symbol: str  # Trading pair symbol (e.g., "BTCUSDT")
    strategy_id: str  # ID of the strategy that generated the signal
    metadata: Dict[str, Any]  # Additional information about the signal
    signal_confidence: float  # Confidence level of the signal (0.0 to 1.0)
    timestamp: int = 0  # Unix timestamp in milliseconds
    
    def __post_init__(self):
        """Validates signal parameters after initialization.
        
        Raises:
            ValueError: If any of the signal parameters are invalid:
                - action not in ["open", "exit", "hold"]
                - side not valid for the action type
                - missing symbol or strategy_id
        """
        if self.action not in ["open", "exit", "hold"]:
            raise ValueError("Action must be either 'open', 'exit', or 'hold'")
            
        if self.action == "hold" and self.side != "none":
            raise ValueError("Side must be 'none' when action is 'hold'")
            
        if self.action != "hold" and self.side not in ["buy", "sell"]:
            raise ValueError("Side must be either 'buy' or 'sell' for open/exit actions")
            
        if not self.symbol:
            raise ValueError("Symbol must be specified")
            
        if not self.strategy_id:
            raise ValueError("Strategy ID must be specified")
    
    
   